### ISSUE TITLE
Compile Time Error

### ISSUE THREAD

**Issue by schun99** [atchekho/harmpi#3]
<img width="938" alt="Screen Shot 2020-11-05 at 12 44 20 PM" src="https://user-images.githubusercontent.com/60271712/98276887-a1ff8400-1f64-11eb-9681-bba96a65f8e0.png">

Hello, I am trying to increase the compile time from the default setting 1000 to 10000 for Bondi 1D problem. I tried this by changing variable _Rout_ in init.c file, but I keep having this error shown in the screen shot. I have tried looking up how to solve, but I am having trouble understanding what is going on. Would you be able to provide any assistance regarding this error? Thank you in advance.

**Comment by schun99** [comment]
@atchekho @rsnemmen

**Comment by atchekho** [comment]
Hi Sophie,

This looks like an OpenMPI bug:

https://github.com/open-mpi/ompi/issues/4336

Could you try updating OpenMPI to the most latest version?

Cheers,
Sasha

**Comment by schun99** [comment]
Hi Professor Tchekhovskoy,

Thank you for your advice. I updated OpenMPI from the one recommended in the tutorial, 2.0.4, to the most latest version, 4.0.5. However, I now get following error as shown in the screen shot below.

<img width="991" alt="Screen Shot 2020-11-09 at 12 36 40 PM" src="https://user-images.githubusercontent.com/60271712/98576328-5e6c8900-2288-11eb-91c1-b0c4c00dd66d.png">

I read the issue you mentioned and tried `ulimit -n 10240`, and it ran well and did not abort the process anymore. I believe this command is increasing the capacity just temporarily because I had to type this command every time I ran a new simulation. Would keeping version 2.0.4 and running `ulimit -n (number)` each time be okay?

**Comment by atchekho** [comment]
Hi Sohee,

I think that 2.0.4 should be fine so long as there are no errors (of
course, running a few basic tests and making sure that all looks good is
always a good idea).

The error in 4.0.5 seems to be related to this:

https://www.open-mpi.org/faq/?category=troubleshooting#missing-symbols

I am afraid I cannot be of more help here -- this seems to be a library
installation problem.

Cheers,
Sasha

**Comment by schun99** [comment]
Thank you very much for your assistance, and I will take a look at it and close this issue. Thank you again.
